// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UserFunctionalityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginInvalidCredentials() {
    driver.get("https://shopsmartcanada.com/");
    driver.findElement(By.cssSelector(".navUser-action:nth-child(3) > .\\_label")).click();
    driver.findElement(By.id("login_email")).click();
    driver.findElement(By.id("login_email")).sendKeys("invalid@email.com");
    driver.findElement(By.id("login_pass")).click();
    driver.findElement(By.id("login_pass")).sendKeys("invalidpw");
    driver.findElement(By.cssSelector(".form-actions > .button")).click();
    assertThat(driver.getTitle(), is("Shop Smart Canada - Sign in"));
  }
  @Test
  public void loginValidCredentials() {
    driver.get("https://shopsmartcanada.com/");
    driver.findElement(By.cssSelector(".navUser-action:nth-child(3) > .\\_label")).click();
    driver.findElement(By.id("login_email")).click();
    driver.findElement(By.id("login_email")).sendKeys("christopher.brunet@ucalgary.ca");
    driver.findElement(By.id("login_pass")).click();
    driver.findElement(By.id("login_pass")).sendKeys("seng637");
    driver.findElement(By.cssSelector(".form-actions > .button")).click();
    assertThat(driver.getTitle(), is("Shop Smart Canada - Order Status"));
  }
  @Test
  public void updateAccountName() {
    driver.get("https://shopsmartcanada.com/");
    driver.findElement(By.cssSelector(".\\_account-user use")).click();
    driver.findElement(By.linkText("Account Settings")).click();
    driver.findElement(By.id("account_firstname")).click();
    {
      WebElement element = driver.findElement(By.id("account_firstname"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("account_firstname")).sendKeys("Test");
    driver.findElement(By.cssSelector(".form-field:nth-child(3) > .form-label")).click();
    driver.findElement(By.cssSelector(".form-actions > .button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 1);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".alertBox-message")));
    }
    assertThat(driver.findElement(By.cssSelector(".alertBox-column > span")).getText(), is("Your account details have been updated."));
    {
      String value = driver.findElement(By.id("account_firstname")).getAttribute("value");
      assertThat(value, is("Test"));
    }
  }
  @Test
  public void signOut() {
    driver.get("https://shopsmartcanada.com/");
    driver.findElement(By.cssSelector(".\\_label:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".alertBox-column > span")).getText(), is("You\\\'ve been logged out of your account successfully."));
  }
}
